name: crypto_project
version: '1.0'
config-version: 2

profile: bigquery_profile

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  crypto_project:
    +dataset: crypto_dataset
    +materialized: table
